# Generated by Django 4.2.4 on 2023-08-18 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_otp_userprofile_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email",
        ),
    ]
